site_name: Automotive Academy Cloud Expert Program
site_url: https://d11ec2722rad1b.cloudfront.net/
site_description: Documentation Site of the Automotive Academy Cloud Expert Program
copyright: msg systems ag Automotive Technology
repo_url: https://github.com/msgoat/cxp-dox-home
repo_name: cxp-dox-home
use_directory_urls: false
markdown_extensions:
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
theme: material
nav:
  - Home: index.md
  - Virtualization:
      - Virtual Machines: virtualization/virtual_machines.md
      - Installing Hyper-V: virtualization/hyperv_install.md
      - Installing VirtualBox: virtualization/vbox_install.md
  - Linux:
      - Linux Introduction: linux/index.md
      - Creating CentOS8 VM on Hyper-V: linux/centos8_create_vm_hyperv.md
      - Installing CentOS8: linux/centos8_install.md
      - Setting up CentOS8: linux/centos8_setup.md
      - Linux Storage Basics: linux/linux_storage_basics.md
      - Adding a new Block Device to CentOS8: linux/centos8_add_volume.md
      - Growing an existing Block Device on CentOS8: linux/centos8_grow_volume.md
  - Docker:
      - Docker Introduction: docker/index.md
      - Getting Started with Docker: docker/docker_introduction.md
      - Docker vs Virtual Machines: docker/docker_vs_virtual_machines.md
      - From Dockerfile to Docker Container: docker/docker_dockerfile_2_container.md
      - From Dockerfile to Docker Container (Walkthrough): docker/docker_dockerfile_2_container_by_example.md
      - Docker Container Storage: docker/docker_storage.md
      - Composing Docker Containers with Docker Compose: docker/docker_compose.md
      - Docker Best Practices: docker/docker_best_practices.md
      - Docker Runtime Scenarios: docker/docker_runtime_scenarios.md
  - Kubernetes:
      - Kubernetes Introduction: kubernetes/index.md
      - Getting Started with Kubernetes: kubernetes/k8s_introduction.md
      - Moving Parts of a Kubernetes Cluster: kubernetes/k8s_clusters.md
      - Kubernetes Basic Object Model: kubernetes/k8s_basic_objects.md
      - Batch processing on Kubernetes: kubernetes/k8s_batch_processing.md
      - Highly available applications with Kubernetes: kubernetes/k8s_pod_availability.md
      - Enforcing Pod Security on Kubernetes: kubernetes/k8s_pod_security.md
      - Role Based Access Control (RBAC) on Kubernetes: kubernetes/k8s_rbac.md
      - Configuring Applications on Kubernetes: kubernetes/k8s_configuring_applications.md
      - Kubernetes CLI kubectl:
          - Administrating Kubernetes clusters with kubectl: kubernetes/kubectl/kubectl_introduction.md
          - Installing kubectl: kubernetes/kubectl/kubectl_install.md
          - Setting up kubectl: kubernetes/kubectl/kubectl_setup.md
          - kubectl commands: kubernetes/kubectl/kubectl_commands.md
      - Install minikube: kubernetes/minikube/minikube_install.md
  - Helm:
      - Helm Introduction: helm/index.md
      - Moving Parts of Helm: helm/helm_moving_parts.md
      - Installing Helm: helm/helm_install.md
      - Helm Commands: helm/helm_commands.md
      - Managing Releases: helm/helm_managing_releases.md
      - Reusing Charts: helm/helm_reusing_charts.md
  - Cluster Tool Stacks:
      - Introducing Tool Stacks: toolstacks/index.md
      - Cluster Ingress Controller:
          - Introduction: toolstacks/ingress/ingress_index.md
      - Cluster Logging:
          - Introduction: toolstacks/logging/logging_index.md
          - Best Practices: toolstacks/logging/logging_best_practices.md
          - Kibana Features: toolstacks/logging/kibana_features.md
      - Cluster Monitoring:
          - Introduction: toolstacks/monitoring/monitoring_index.md
          - Metrics Catalog: toolstacks/monitoring/monitoring_metrics.md
          - Prometheus Metric Types: toolstacks/monitoring/prometheus_metric_types.md
          - Exposing Java Application to Prometheus: toolstacks/monitoring/monitoring_applications.md
          - Best Practices: toolstacks/monitoring/monitoring_best_practices.md
      - Cluster Tracing:
          - Introduction: toolstacks/tracing/tracing_index.md
          - Tracing Java Applications: toolstacks/tracing/tracing_applications.md
          - Best Practices: toolstacks/tracing/tracing_best_practices.md
      - Cluster Identity&Access Management: toolstacks/iam/iam_index.md
  - Cloud Basics:
      - Introduction: cloud/index.md
      - Cloud Capabilities: cloud/cloud_capabilities.md
      - Cloud Terminology: cloud/cloud_terminology.md
      - Cloud Service Categories: cloud/cloud_service_categories.md
  - AWS:
      - Introduction: aws/index.md
      - Facts & Figures: aws/aws_facts_figures.md
      - AWS Best Practices: aws/aws_best_practices.md
      - AWS Accounts: aws/aws_accounts.md
      - AWS Users:
          - User Account Basics: aws/iam/aws_users.md
          - Setting up a Console User Account: aws/iam/aws_console_user_setup.md
          - Setting up a Programmatic User Account: aws/iam/aws_programmatic_user_setup.md
      - AWS Virtual Private Cloud (VPC):
          - VPC Basics: aws/vpc/vpc_basics.md
          - VPC Reference Blueprint: aws/vpc/vpc_blueprint.md
          - VPC Extended Networking:
              - Introduction: aws/vpc/vpc_extended_networking.md
              - VPC to AWS services: aws/vpc/vpc_2_aws_services.md
              - VPC to VPC: aws/vpc/vpc_2_vpc.md
              - Site to Site: aws/vpc/site_2_site.md
      - AWS DNS with Route53:
          - DNS Basics: aws/route53/dns_basics.md
          - Route 53 Introduction: aws/route53/aws_r53_intro.md
      - AWS Virtual Machines (EC2):
          - EC2 Basics: aws/ec2/ec2_basics.md
          - EC2 Pricing Options: aws/ec2/ec2_purchasing_options.md
          - EC2 Best Practices: aws/ec2/ec2_best_practices.md
          - Creating an EC2 instance: aws/ec2/ec2_create_instance.md
      - AWS Block Storage (EBS):
          - Creating an EBS volume: aws/ebs/ebs_create_volume.md
          - Resizing an EBS volume: aws/ebs/ebs_resize_volume.md
      - AWS Landing Zones:
          - AWS Landing Zones in a Nutshell: aws/landingzone/index.md
  - Azure:
      - Introduction: azure/index.md
      - Facts & Figures: azure/az_facts_figures.md
      - Get Started: azure/az_get_started.md
      - Naming Rules & Conventions: azure/az_naming.md
      - Azure Virtual Networks (VNet):
          - VNet Basics: azure/vnet/vnet_basics.md
          - VNet Extended Networking:
              - VNet-to-VNet with VNet Peering: azure/vnet/az_vnet_peering.md
              - Point-to-Site/Site-to-Site with VPN Gateways: azure/vnet/az_vpn_gateway.md
              - Site-to-Site with ExpressRoute: azure/vnet/az_vpn_express_route.md
      - Azure Virtual Machines (VM):
          - VM Basics: azure/vm/vm_basics.md
      - Azure DNS:
          - DNS Basics: azure/dns/dns_basics.md
      - Azure AKS:
            - AKS Basics: azure/aks/aks_basics.md
  - Infrastructure as Code:
      - Introduction: iac/index.md
      - Tools:
          - Terraform: terraform/index.md
          - Packer: packer/index.md
  - SSH:
      - SSH Primer: ssh/ssh_primer.md
      - Connecting to Linux VMs: ssh/ssh_connect_to_vms.md
      - PuTTY Primer: ssh/putty_primer.md
      - Managing Connections with PuTTY: ssh/putty_managing_connections.md
      - Managing SSH Keys with PuTTY: ssh/putty_managing_ssh_keys.md
      - Creating SSH Keys with ssh-keygen: ssh/ssh_create_ssh_keys.md